#! /bin/bash

export SSHRCD="$SSHRC_CONFIG/sshrc.d"

# Correct username
if [ "$USER" != "$(whoami)" ]; then
  USER=$(whoami)
fi

source $SSHRCD/.bash_profile
source $SSHRCD/.bashrc
source $SSHRCD/prompt

# Attach tmux upon session creation
if which tmux >/dev/null 2>&1; then
  tmuxrc-create-or-attach-session
fi
