source $HOME/.config/nvim/mappings.vim
source $HOME/.config/nvim/plugins.vim
source $HOME/.config/nvim/settings.vim
source $HOME/.config/nvim/plug-configs/airline.vim
source $HOME/.config/nvim/plug-configs/closetags.vim
source $HOME/.config/nvim/plug-configs/coc.vim
source $HOME/.config/nvim/plug-configs/file-header.vim
source $HOME/.config/nvim/plug-configs/floaterm.vim
source $HOME/.config/nvim/plug-configs/fzf.vim
source $HOME/.config/nvim/plug-configs/gitgutter.vim
source $HOME/.config/nvim/plug-configs/nerd-commenter.vim
source $HOME/.config/nvim/plug-configs/netrw.vim
source $HOME/.config/nvim/plug-configs/quickscope.vim
source $HOME/.config/nvim/plug-configs/vim-rooter.vim
source $HOME/.config/nvim/plug-configs/start-screen.vim
source $HOME/.config/nvim/plug-configs/vim-wiki.vim
source $HOME/.config/nvim/plug-configs/which-key.vim
